service: apollo-lambda

package:
  individually: false

custom:
  serverless-offline:
    useChildProcesses: true
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs18.x
  stage: bff

functions:
  sign-in:
    handler: src/rest/auth/sign-in.handler
    events:
      - http:
          path: /rest/auth/sign-in
          method: POST
          cors: true

  sign-up:
    handler: src/rest/auth/sign-up.handler
    events:
      - http:
          path: /rest/auth/sign-up
          method: POST
          cors: true

  confirm-sign-up:
    handler: src/rest/auth/confirm-sign-up.handler
    events:
      - http:
          path: /rest/auth/confirm-sign-up
          method: POST
          cors: true

  forgot-password:
    handler: src/rest/auth/forgot-password.handler
    events:
      - http:
          path: /rest/auth/forgot-password
          method: POST
          cors: true

  forgot-password-submit:
    handler: src/rest/auth/forgot-password-submit.handler
    events:
      - http:
          path: /rest/auth/forgot-password-submit
          method: POST
          cors: true

  graphql:
    handler: src/graphql/index.handler
    events:
      - http:
          path: /graphql
          method: GET
          cors: true
          integration: lambda-proxy
      - http:
          path: /graphql
          method: POST
          cors: true
          integration: lambda-proxy

plugins:
  - serverless-plugin-typescript
  - serverless-bundle
  - serverless-offline
