name: Deploy Prod
on:
  push:
    branches:
      - main

jobs:
  call-deploy-bff:
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: prod
      CERTIFICATE_ARN: arn:aws:acm:us-east-1:223889111609:certificate/02144fb7-e13f-4117-9b75-1f213c36f3ea
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
