on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      CERTIFICATE_ARN:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-bff:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      CERTIFICATE_ARN: ${{ inputs.CERTIFICATE_ARN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Deploy on AWS
        run: |
          cd deploy
          yarn install
          npx cdk deploy --require-approval never
